---
abstract: 'Simple method to generate Excel files from 2D arrayrefs'
author:
  - "'Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Spreadsheet-DataToExcel
provides:
  Spreadsheet::DataToExcel:
    file: lib/Spreadsheet/DataToExcel.pm
    version: 0.0103
requires:
  Class::Data::Accessor: 0.04004
  Spreadsheet::WriteExcel: 2.25
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
